### ISSUE TITLE
Jason vs. Poison

### ISSUE THREAD

**Issue by brianbroderick** [joken-elixir/joken#203]
Phoenix 1.4 has moved to using Jason instead of Poison.  What are the chances that Joken could be configured to use Jason as well?

**Comment by victorolinasc** [comment]
Hey @brianbroderick ! 

We are on the verge of releasing versino 2.0 (still some minor nitpicks on my part before that) but it will certainly come with Jason as a default. Its dependency will still be optional as we don't want to force that but it will be as easy as adding the dep.

If you want to know how to use Jason with current Joken 1.x the implementation is [here](https://github.com/joken-elixir/joken/blob/master/lib/joken/jose_jason.ex). It is actually a way to configure erlang-jose.

If that is okay I'll close this issue.

**Comment by brianbroderick** [comment]
Thanks for the quick feedback! I'm looking forward to version 2!
