### ISSUE TITLE
multiple public keys

### ISSUE THREAD

**Issue by brianmay** [joken-elixir/joken#207]
Seems Google provides multiple public certificates to use for verifying tokens, in different formats:

* https://www.googleapis.com/oauth2/v3/certs
* https://www.googleapis.com/oauth2/v1/certs

This token is supplied by Google and required to verify the user of the Google Actions service.

Just wondering if there is any easy way of using these with Joken? So far I have used the 2nd certificate only, and it appears to work for me(TM), however not sure this will always be the case.

This is what I currently have:

```
config :joken,
  rs256: [
    signer_alg: "RS256",
    key_pem: """
    -----BEGIN CERTIFICATE-----
    MIIDJjCCAg6gAwIBAgIIHjqNyx42LJgwDQYJKoZIhvcNAQEFBQAwNjE0M
    AxMrZmVkZXJhdGVkLXNpZ25vbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50L
    Fw0xODEyMDMxNDQ5MTNaFw0xODEyMjAwMzA0MTNaMDYxNDAyBgNVBAMTK
    YXRlZC1zaWdub24uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wggEiM
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCUPM6L+urBOw4LZRMMoI8tAEurk
    AQWC2igQ0B2bBaHT+2IC1wssGlJ5ziT0xymztzHcb+5cGb3LdOAIdX3K4
    ME6ule51JBziD8HP9o5TeNXryN0rfvm14por0iYm0WM9k1WirpdX1RL4C
    MkfPsJLOHDPtDql0vtCyHcytGoDBnEhtYjsN3eNk7V//n1sTuO6/D6mAc
    VvjXfa1naL/wPw2K4cGD9lVUl2SfehcBBkHjolHo+5TJNQSgacFbVlmFo
    3Iolmcl9eoA+eITu36iYw5BlLtUVo8BKXJyc8vfOfIEt7J67LD27AgMBA
    MAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMBYGA1UdJQEB/wQMM
    AQUFBwMCMA0GCSqGSIb3DQEBBQUAA4IBAQAD+Jguiz7SCk298W1NUIyYr
    kbFCrZShTh28PLbhJPb8rkO4FzylgTenDV5blrK+gg6RWnEHbSrIL/JXc
    NWINAsWWJu66qm65iRvfVS4i4lHN+XxDDKMewUq3Eq+NmJXLDLMkPzlDi
    0xu2DddeJiXHQfdNLWo8BskVwYOg+k5sqv7w4lwxzNWoVAqe3aDkCoPiM
    dxq8TDITYuX+PVHMPPNp4fO+s3rqETKmTVSiu36X0/RHo1+MmLmEiFgi5
    2Y9ekOhRYn2itabUYH7y7Vn1QwyYHerwE4XXdUgGCh+x28EkQ+TYDH58
    -----END CERTIFICATE-----
    """
  ]
```

**Comment by victorolinasc** [comment]
Hi @brianmay (what a name!!! I'm a fan hehe)!

These formats, standards and so on are a lot confusing unfortunately... Let's try to get to the bottom of it.

Both URLs have different contents:
- v1 is a map of cert_id -> certificate
- v3 follows the JWKS specification where it has a list of JWK (JSON Web Keys). This is a standard that Joken knows how to read properly.

So on v1 the certificates are PEM encoded. That means they can contain a lot of things like x509, private and public keys and so on. See, for example, this answer https://stackoverflow.com/a/45398281/1397594.

Being PEM encoded means `erlang-jose` can parse it but results will vary cause PEM is a container and not a standardized one. It is basically a pattern of blocks of base64 bytes. Inside those blocks you still have DER or BER encoded (or other formats...) data.

So, to answer your question properly: v1 should not work :) v3 is fully compatible. As a matter of fact, you can use a hook to verify tokens that are signed with v3 keys. Take a look at `joken_jwks` but I'll let you know beforehand that it cannot be used with rc3 yet. Use Joken 2.0.0-rc2 and in a near future we will update and release both as final versions.

Does that help you?

**Comment by brianmay** [comment]
Thanks for you response. So if I understand correctly, I should be using the v3 format, which I am not actually doing right now, but it won't work unless I downgrade or wait for a fix.

Are you able to provide an example of how to define a v3 format certificate?

I see you gave a reference to `joken_jwks`, but not really sure what you are referring to, sorry.

**Comment by victorolinasc** [comment]
@brianmay let me explain a little better.

v1 is not meant for JWTs validation. When you need to validate a JWT from an auth server *usually* it means the provider has a valid JWKS URI. That is a list of public keys the server uses to generate the token.

v3 is the endpoint for Google's JWKS URI. It is listed as the JWKS_URI on [its discovery document](https://developers.google.com/identity/protocols/OpenIDConnect#discovery).

So, there are a few things you can do to validate a token issued by Google:
1. Copy the public key parameters in [here](https://www.googleapis.com/oauth2/v3/certs) to a `Joken.Signer` configuration;
2. Use a library to dynamically fetch these parameters and build a cache with them (that is what joken_jwks is meant to do);

For option number 1 you could do something like [this part](https://hexdocs.pm/joken/2.0.0-rc3/signer.html#all-other-keys) of the documentation says. It would look something like:

```elixir
config joken, google_key_0: [
  signer_alg: "RS512",
  jose_extra_headers: %{"kid" => "463fe480c3c5839bbb15861e08c32d187faf9a56"},
  key_map: %{
  "e" => "AQAB",
  "kty" => "RSA",
  "n" =>
    "xnAUUvtW3ftv25jCB-hePVCnhROqH2PACVGoCybdtMYTl8qVABAR0d6T-BRzVhJzz0-UvBNFUQyVvKAFxtbQUZN2JgAm08UJrDQszqz5tTzodWexODdPuoCaWaWge_MZGhz5PwWd7Jc4bPAu0QzSVFpBP3CovSjv48Z2Eq0_LHXVjjX_Az-WaUh94mXFyAxFI_oCygtT-il1-japS3cXJJh0WddT3VKEBRYHmxDJd_LYE-KXQt3aTDhq0vI9sG2ivtFj0dc3w_YBdr4hlcr42ujSP3wLTPpTjituwHQhYP4j-zqu7J3FYaIxU4lkK9Y_DP27RxffFI9YDPJdwFkNJw",
}]
```

For option 2 you could use `joken_jwks`:

```elixir
defmodule MyToken do
  use Joken.Config

  add_hook(JokenJwks, jwks_url: "https://www.googleapis.com/oauth2/v3/certs")

  def token_config do
    # your token config
  end
end

MyToken.verify_and_validate(google_token)
```

If you are going with option 2, than you should use either Joken 2.0.0-rc2 or wait until we fix the compatibility hehe.

Does that help?

**Comment by brianmay** [comment]
OK, thanks for your help. Currently trying option 2, and I downgraded to 2.0.0-rc2, and installed JokenJwks via git (doesn't seem to be on git yet), and so far it appears to be working. Fingers crossed. Thanks.

**Comment by victorolinasc** [comment]
Hey @brianmay! Awesome! 

I'll close the issue now but if anything comes back just reopen it or open a new one.
