### ISSUE TITLE
Signer is empty if it is not available at compile time

### ISSUE THREAD

**Issue by sgtpepper43** [joken-elixir/joken#211]
When `using` `Joken.Config`, it expects the default signer to be defined at compile time. But some of as are relying on `env` vars that might not exist at compile time, and even then can be swapped out without recompiling. If [this line](https://github.com/joken-elixir/joken/blob/master/lib/joken/config.ex#L150) was changed to be a function rather than a module attribute, that would alleviate this problem.

Actually if that logic was just moved into the existing `__default_signer__`, that would probably work fine. Unless parsing the signer config is an expensive operation and it really needs to be cached in a module attribute or something.

**Comment by sgtpepper43** [comment]
But I'd hate to break any performance optimizations for everyone else, so I'll see if we can either have both or try tl prove that it's just as performant with the PR I've got open

**Comment by victorolinasc** [comment]
@fireproofsocks thanks for the feedback! I will look into making the examples clearer about that.

Will also update the documentation about what goes into `config.exs` and friends.

For your specific use case, you could simply use:

```elixir
config :joken, default_signer: "secret"
```
This is a "shortcut" that I've just noticed is not on the docs Oo. That way the algorithm will be HS256.

For all other cases, you can use keyword lists for configuring your signers like said [here](https://hexdocs.pm/joken/signer.html#content).

So, let's say you want to use HS512 (symmetric key). Then you could do:

```elixir
config :joken, default_signer: [
   signer_alg: "HS512",
   key_octet: "MyS3cr3t"
]
```

And that's it! 

About using the default signer, it is meant to be used wihtout needed to specify keys. Look at [this test](https://github.com/joken-elixir/joken/blob/master/test/use_config_test.exs#L13). It does not specify a key. Which one it is using though? [This one!](https://github.com/joken-elixir/joken/blob/master/config/test.exs#L32).

Hope that clears for now! I'll review the docs one more time.

Once again, thanks for the feedback.

**Comment by fireproofsocks** [comment]
THANK YOU! That example got me to a place where things are working and in hindsight I can see what was meant by the docs.  It would be super-helpful to include examples of at least each type of the keys (HMAC, RSA, EC) because the options used for each are extremely different.

**Comment by victorolinasc** [comment]
I've thought about an example for each type of key but are already better documented by the specs of JWA and JWK IMHO.

There is the most used example of RSA too [here](https://hexdocs.pm/joken/signer.html#all-other-keys). But there are many use cases and it would be gigantic... for example, RSA can be public and private as can all the others and their parameters are different. 

I am thinking of delaying that to when we come up with crypto adapters. I really think we can squeeze a bit more performance if we use `:crypto` and `:public_key` directly... but that is on my maybe todo list heheh. [This issue](https://github.com/potatosalad/erlang-jose/issues/43) made me think about that.

But I will surely improve the docs in a while. 

Regards!

**Comment by fireproofsocks** [comment]
For what it's worth, I struggled for a full day trying to make joken work with the existing documentation and I failed until the example you shared above finally made me understand how you were relating the various parts together.  The "example" at https://hexdocs.pm/joken/signer.html#all-other-keys is not an example, it's just a map out of context.  I had no idea how that was supposed to fit into the config or module.  Perhaps a more useful RSA example would be one that uses the standard RSA SSH key that Github utilizes (and included full config and module counterparts).  Just showing a couple more _full_ examples from beginning to end will help users understand what options need to be there and how to vary them when the signer changes.  I ended up in a loop jumping between the Joken.Signer and Joken.Config pages when one would refer to the other for specifics.   

Remember: "Your docs have too many examples" said no developer in history ever.

**Comment by victorolinasc** [comment]
> Remember: "Your docs have too many examples" said no developer in history ever.

Hahaha you are 100% right about that!

I'll add more examples and "real" ones... not just a map without context. 

Thanks once again for the feedback. Perhaps we'd better open a new issue about signer example configuration. What do you think? We've already side-tracked about the intent here.

**Comment by fireproofsocks** [comment]
Haha - yes, of course!  I opened issue #214 and I've already started work on a PR.
