### ISSUE TITLE
Could not recognize the signer algo

### ISSUE THREAD

**Issue by vans163** [joken-elixir/joken#223]
```
Joken.Signer.create("RS256", "secret")

**** (Joken.Error) Couldn't recognize the signer algorithm.

Possible values are:

["HS256", "HS384", "HS512", "RS256", "RS384", "RS512", "ES256", "ES384", "ES512", "PS256", "PS384", "PS512", "Ed25519", "Ed25519ph", "Ed448", "Ed448ph"]

    lib/joken/signer.ex:93: Joken.Signer.create/3
**
```

**Comment by victorolinasc** [comment]
This is because the algorithm RS*** uses public/private keys for verifying/signing a token.

More info can be seen on the asymmetric crypto guide [here](https://hexdocs.pm/joken/assymetric_cryptography_signers.html#content).

The error message could be tweaked to be more specific. I'll keep this open until I get around it.

**Comment by autodidaddict** [comment]
I'm having the same problem. I want to create an `Ed25519` signer to verify tokens but I can't figure out how to create it, the `create` function . just gives me that error about an unrecognized signer algorithm.

**Comment by victorolinasc** [comment]
Hi @autodidaddict 

The Edwards curves family of algorithms are not built-in and need some extra dependencies to work. This is the way JOSE works. More information may be found here: https://github.com/potatosalad/erlang-jose/blob/master/ALGORITHMS.md

Although OTP now supports edwards curves (OTP 21 with a recent OpenSSL/BoringSSL) this detection is not built-in in JOSE.

We are planning on providing our own implementation of JWA in the future to make it more easily pluggable but time is never a comodity unfortunately.

@vans163 Did that solve your issue? Can I close this one?

**Comment by autodidaddict** [comment]
@victorolinasc I'm not native to the Elixir ecosystem so I'm struggling a bit with the solution here. I added `libdecaf` as a dependency to my project, but I apparently can't compile `libsodium` when I add it as a dependency. Do I need both? With just libdecaf present I still get the same error.

**Comment by victorolinasc** [comment]
For `Ed25519` you need both. They are C libraries that JOSE binds to in order to delegate the execution of this algorithm. 

Unfortunately it is a bit outside of my scope too as those libraries have themselves other dependencies that are OS dependent.

**Comment by bderooms** [comment]
Is it a similar error when I receive: 
iex(3)> signer = Joken.Signer.create("RS512", %{"pem" => pem})
** (FunctionClauseError) no function clause matching in :jose_jwk.from_pem/1 

Tried to pass it as a string or pass it through JOSE.JWK.from_pem_file first. Both don't work. 
Do I need to install something first?

**Comment by victorolinasc** [comment]
@bderooms this is a different issue... Probably related to your pem variable. It seems that it is not a `String.t()` in your case.

For instance:

```elixir
:jose_jwk.from_pem(123456)
** (FunctionClauseError) no function clause matching in :jose_jwk.from_pem/1    
    
    The following arguments were given to :jose_jwk.from_pem/1:
    
        # 1
        123456
    
    (jose) src/jose_jwk.erl:371: :jose_jwk.from_pem/1
```

Pem should contain a valid PEM encoded key.

**Comment by victorolinasc** [comment]
@vans163 I'll close this issue for now. If anything, please re-open this. THanks!

**Comment by vans163** [comment]
I stopped using Joken and just implemented the signature check myself, I needed it for JWT validation. So cannot comment if its fixed..

**Comment by adamu** [comment]
> The error message could be tweaked to be more specific. I'll keep this open until I get around it.

I've just run in to this. The error is specifically confusing, because the list of supported algorithms includes the algorithm that has been rejected.

**Comment by ostinelli** [comment]
I'm getting a similar message:

```
Couldn't recognize the signer algorithm.
Possible values are:

["HS256", "HS384", "HS512", "RS256", "RS384", "RS512", "ES256", "ES384", "ES512", "PS256", "PS384", "PS512", "Ed25519", "Ed25519ph", "Ed448", "Ed448ph"]
```

Trying to use "HS256" which should be pretty common (HMAC using SHA256). Can someone tell me what library / other do I need to bring in to enable this algorithm?

Thank you.

**Comment by victorolinasc** [comment]
@adamu I am curious as to which error you were getting with `Joken`. If possible can you paste a simple example?

For instance:

```elixir
pem = File.read!("private_key.pem")
signer = Joken.Signer.create("RS256", %{"pem" => pem})
```

Does that not work for you?

**Comment by adamu** [comment]
It was two years ago, let me see... I just tried your suggestion and it works. It's possible I was passing the binary directly instead of a map. If I do that, the error message does say that a map is required:

    Joken.Signer.create("RS256", pem)

> ** (Joken.Error) A map was expected for the key parameter in the signer creation.
> This is mandatory for: ["RS256", "RS384", "RS512", "ES256", "ES384", "ES512", "PS256", "PS384", "PS512", "Ed25519", "Ed25519ph", "Ed448", "Ed448ph"].
> 
>     (joken 2.4.1) lib/joken/signer.ex:100: Joken.Signer.create/3

However, on the version at the time, 2.2.0. it doesn't:

> 
> ** (Joken.Error) Couldn't recognize the signer algorithm.
> 
> Possible values are:
> 
> ["HS256", "HS384", "HS512", "RS256", "RS384", "RS512", "ES256", "ES384", "ES512", "PS256", "PS384", "PS512", "Ed25519", "Ed25519ph", "Ed448", "Ed448ph"]
> 
>     (joken 2.2.0) lib/joken/signer.ex:93: Joken.Signer.create/3

**Comment by victorolinasc** [comment]
SOrry @adamu ! I was trolled by email notifications here ...

Someone commented and then deleted here... I got the email, came here to check and thought it was you heheh sorry about this! 

THanks for confirming the fix :)
