### ISSUE TITLE
How do I make validation fail if a claim is not present at all?

### ISSUE THREAD

**Issue by mathiasose** [joken-elixir/joken#224]
So if a claim is present, I can use my own validation function to accept or reject based on the value. Cool. But if the claim isn't present at all, then `verify_and_validate` says the token is valid, because there was no input to run the validation function on, therefore the validation never failed? How do I make a claim required?

In my application Joken is only used for validation, with another service written in another language doing token generation. Taking a black box approach to the other service, if I can't enforce that the claims are added during token generation, I must check that they are present during validation instead.

I have reduced my problem down to this minimal example, with two passing tests and one failing. I used `sub` as an example here, but it goes for all types of claim really:

```elixir
defmodule TokenTest do
  use DataCase

  defmodule ProperToken do
    use Joken.Config

    @impl true
    def token_config do
      %{}
      |> Joken.Config.add_claim("sub", fn -> nil end, fn val, _, _ -> val == true end)
    end
  end

  defmodule EmptyToken do
    use Joken.Config

    @impl true
    def token_config, do: %{}
  end

  describe "dummy tokens rejected" do
    test "accept token with sub true" do
      signer = Joken.Signer.create("HS256", "a key")

      {:ok, token, _} = EmptyToken.generate_and_sign(%{"sub" => true}, signer)

      {:ok, _} = ProperToken.verify_and_validate(token, signer)
    end

    test "reject token with sub false" do
      signer = Joken.Signer.create("HS256", "a key")

      {:ok, token, _} = EmptyToken.generate_and_sign(%{"sub" => false}, signer)

      {:error, _} = ProperToken.verify_and_validate(token, signer)
    end

    test "reject token with no sub" do
      signer = Joken.Signer.create("HS256", "a key")

      {:ok, token, claims} = EmptyToken.generate_and_sign(%{}, signer)

      # ok
      assert "sub" not in Map.keys(claims)

      # MatchError
      {:error, _} = ProperToken.verify_and_validate(token, signer)
    end
  end
end
```

**Comment by victorolinasc** [comment]
Hi @mathiasose ! There is an enhancement to Joken to pass options and one of them will certainly be to tell if a claim is mandatory.

Meanwhile, you can use an after validate hook to do exactly that. It would look something like this:

```elixir
defmodule MyExternalServiceToken do
  use Joken.Config

  @impl true
  def token_config do
    # your validations for known claims
  end

  @impl Joken.Hooks
  def after_validate(_, {:ok, claims} = result, input) do
    # validate claim presence only
  end
  def after_validate(_, result, input), do: {:cont, result, input}
end
```

See documentation for hooks [here](https://hexdocs.pm/joken/Joken.Hooks.html#content).

If this works for you I'll close the issue, ok?

**Comment by mathiasose** [comment]
Thanks! This is what I came up with, which works for my tests cases:

```elixir
  @required_claims MapSet.new(["sub", "aud", "exp", "iat", "nbf"])

  @impl Joken.Hooks
  def after_validate(_, {:ok, claims} = result, input) do
    claims =
      claims
      |> Map.keys()
      |> MapSet.new()

    @required_claims
    |> MapSet.subset?(claims)
    |> case do
      true ->
        {:cont, result, input}

      _ ->
        diff = MapSet.difference(@required_claims, claims) |> MapSet.to_list()
        {:halt, {:error, [message: "Invalid token", missing_claims: diff]}}
    end
  end

  def after_validate(_, result, input), do: {:cont, result, input}
```

**Comment by jsmestad** [comment]
> There is an enhancement to Joken to pass options and one of them will certainly be to tell if a claim is mandatory.

Is this enhancement somewhere? I looked through the open PRs and recent commits and do not see it. I think all claims should be required by default and only opt in to making them optional. Seems to better follow the principle of 'secure by default'

**Comment by victorolinasc** [comment]
Hi @jsmestad ! Just seen your comment. Sorry for not commenting earlier.

I am thinking of a release plan to add that behaviour...

1. Add the hook to Joken 2.x series and document it.
2. Change the default behaviour and add parsing of claims options on 3.x series

Since this is a breaking change (in behaviour and not API) I think this is safer. What do you think? I am reopening this issue until we sort it out.

**Comment by victorolinasc** [comment]
I will release a minor version with the first step on this. Then we can think of what we want for version 3.x.

I'll open an issue about a possible version 3.x.
