### ISSUE TITLE
Release new patch version

### ISSUE THREAD

**Issue by whatyouhide** [joken-elixir/joken#226]
Hey folks, we're using Joken and would love if you could cut a patch release that fixes the compilation warning in https://github.com/joken-elixir/joken/commit/91b3f2560d2f5b88230926cab0f674bcf237109a, removes the Jason hard dependency, and so on. Let me know if I can help in any way! 💟

**Comment by victorolinasc** [comment]
Hi @whatyouhide ! Sure... my bad for holding it so long... 

I was at your talk yesterday on ElixirBrasil! Great one!

I'll be cutting a release now. Once again, sorry for the wait.

**Comment by victorolinasc** [comment]
https://github.com/joken-elixir/joken/releases/tag/v2.1.0
https://hex.pm/packages/joken/2.1.0

Let me know if anything goes wrongfully. I'll be closing this now!

**Comment by whatyouhide** [comment]
Hey @victorolinasc, ahaha no idea you were at Elixir Brasil!! Small world 😄 Anyways, thanks so much for the release, appreciate it 💟
