### ISSUE TITLE
High System CPU in verify_and_validate

### ISSUE THREAD

**Issue by Shayon** [joken-elixir/joken#242]
When calling `Joken.verify_and_validate/3` more than 1.5k times per second we see an exponential increase in System CPU utilization.  When doing some debugging we found that most of the BEAM schedulers are waiting on a `futex`.  No matter how much CPU we throw at this we still get the same results.  When the requests per second drop back below the threshold CPU returns to normal.  We are using `ES512`.  Is this expected with this many requests per second?

* Base System OS and version: `Ubuntu 16.04.6 LTS`
* Docker container OS and version: `Alpine 3.9.4`
* Erlang version: `Erlang/OTP 22.0.7`
* Elixir version: `1.8.2`
* Joken version: `2.1.0`
* Jose version: `1.9.0`

Screen shot of our cores from `htop`:
![Screenshot-20190806102029-1876x263](https://user-images.githubusercontent.com/1694356/62561992-27155e00-b835-11e9-8b29-475d0d89d4aa.png)

Screenshot of `perf top`
![Screenshot-20190806102008-745x360](https://user-images.githubusercontent.com/1694356/62562041-40b6a580-b835-11e9-9fb3-921261ab0f6d.png)

Here is a trace on a scheduler thread:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 96.49   11.312752          77    146110     28694 futex
  0.88    0.102996         107       961           epoll_pwait
  0.49    0.057893          33      1781       779 recvfrom
  0.46    0.053771          19      2800           sched_yield
  0.44    0.051890          67       778           writev
  0.36    0.042329          24      1770           epoll_ctl
  0.31    0.035794          22      1633      1633 madvise
  0.28    0.032452          39       833           sendto
  0.18    0.020794        1890        11           munmap
  0.06    0.006728          33       201           write
  0.03    0.003113         389         8           mmap
  0.01    0.001727          45        38           timerfd_settime
  0.01    0.000664          17        38        19 read
  0.00    0.000460          22        21           getsockopt
  0.00    0.000315          21        15           setsockopt
  0.00    0.000083          42         2           shutdown
  0.00    0.000000           0         1           close
  0.00    0.000000           0         1           getpeername
------ ----------- ----------- --------- --------- ----------------
100.00   11.723761                157002     31125 total
```

here is an `msacc` captured during the problem:
```
:msacc.start(10000);:msacc.print()
Average thread real-time    :  10019889 us
Accumulated system run-time : 314610845 us
Average scheduler run-time  :   9679368 us

        Thread      aux check_io emulator       gc    other     port    sleep

Stats per thread:
     async( 0)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
       aux( 1)    0.84%    0.51%    0.00%    0.00%    0.01%    0.00%   98.64%
dirty_cpu_( 1)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_( 2)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_( 3)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_( 4)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_( 5)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_( 6)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_( 7)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_( 8)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_( 9)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(10)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(11)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(12)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(13)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(14)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(15)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(16)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(17)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(18)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(19)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(20)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(21)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(22)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(23)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(24)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(25)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(26)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(27)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(28)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(29)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(30)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_cpu_(31)    0.00%    0.00%    0.01%    1.89%    0.02%    0.00%   98.08%
dirty_cpu_(32)    0.00%    0.00%    0.01%    5.73%    0.25%    0.00%   94.01%
dirty_io_s( 1)    0.00%    0.00%   12.42%    0.00%   25.63%    0.00%   61.95%
dirty_io_s( 2)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_io_s( 3)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_io_s( 4)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_io_s( 5)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_io_s( 6)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_io_s( 7)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_io_s( 8)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_io_s( 9)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
dirty_io_s(10)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
      poll( 0)    0.00%    1.29%    0.00%    0.00%    0.00%    0.00%   98.71%
 scheduler( 1)    1.50%    0.14%   91.20%    1.03%    2.23%    1.59%    2.31%
 scheduler( 2)    0.61%    0.10%   91.87%    1.20%    1.42%    2.23%    2.57%
 scheduler( 3)    0.61%    0.12%   91.88%    1.09%    1.60%    1.91%    2.78%
 scheduler( 4)    0.72%    0.13%   89.88%    1.05%    1.76%    2.09%    4.37%
 scheduler( 5)    0.80%    0.11%   91.81%    1.30%    1.46%    2.13%    2.38%
 scheduler( 6)    0.67%    0.13%   91.19%    1.17%    1.75%    1.89%    3.19%
 scheduler( 7)    0.55%    0.12%   90.48%    1.12%    1.60%    2.50%    3.63%
 scheduler( 8)    0.77%    0.10%   91.42%    1.09%    1.48%    2.11%    3.02%
 scheduler( 9)    0.64%    0.13%   91.87%    1.16%    1.38%    2.15%    2.68%
 scheduler(10)    0.57%    0.12%   91.91%    1.12%    1.65%    1.80%    2.83%
 scheduler(11)    0.78%    0.13%   91.07%    1.12%    1.57%    2.03%    3.31%
 scheduler(12)    0.71%    0.10%   91.48%    1.14%    1.49%    1.69%    3.39%
 scheduler(13)    0.74%    0.11%   91.59%    1.05%    1.48%    1.99%    3.04%
 scheduler(14)    0.50%    0.10%   90.86%    1.00%    1.79%    1.77%    3.97%
 scheduler(15)    0.74%    0.13%   90.70%    1.38%    1.51%    1.85%    3.70%
 scheduler(16)    0.76%    0.12%   90.41%    1.06%    1.56%    2.25%    3.83%
 scheduler(17)    0.73%    0.10%   91.55%    1.06%    1.46%    1.67%    3.43%
 scheduler(18)    0.76%    0.12%   91.57%    1.06%    1.58%    1.60%    3.30%
 scheduler(19)    0.66%    0.12%   90.85%    1.25%    1.43%    1.73%    3.95%
 scheduler(20)    0.62%    0.12%   91.00%    1.25%    1.46%    1.80%    3.77%
 scheduler(21)    0.54%    0.10%   92.05%    1.07%    1.52%    1.64%    3.07%
 scheduler(22)    0.71%    0.11%   91.44%    1.02%    1.62%    1.98%    3.12%
 scheduler(23)    0.65%    0.12%   91.58%    1.12%    1.55%    2.09%    2.89%
 scheduler(24)    0.50%    0.11%   90.46%    1.28%    1.81%    1.77%    4.07%
 scheduler(25)    0.67%    0.11%   90.16%    1.10%    1.66%    2.20%    4.09%
 scheduler(26)    0.52%    0.11%   91.45%    1.04%    1.63%    1.66%    3.59%
 scheduler(27)    0.71%    0.11%   91.01%    1.05%    1.70%    1.90%    3.52%
 scheduler(28)    0.61%    0.11%   92.03%    1.14%    1.73%    1.44%    2.94%
 scheduler(29)    0.75%    0.11%   91.47%    1.14%    1.48%    1.85%    3.20%
 scheduler(30)    0.74%    0.11%   91.39%    1.06%    1.74%    1.89%    3.07%
 scheduler(31)    0.69%    0.11%   91.29%    1.06%    1.69%    1.94%    3.22%
 scheduler(32)    0.73%    0.11%   89.41%    1.06%    1.77%    1.84%    5.08%

Stats per type:
         async    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
           aux    0.84%    0.51%    0.00%    0.00%    0.01%    0.00%   98.64%
dirty_cpu_sche    0.00%    0.00%    0.00%    0.24%    0.01%    0.00%   99.75%
dirty_io_sched    0.00%    0.00%    1.24%    0.00%    2.56%    0.00%   96.20%
          poll    0.00%    1.29%    0.00%    0.00%    0.00%    0.00%   98.71%
     scheduler    0.70%    0.12%   91.20%    1.12%    1.61%    1.91%    3.35%
```

Please let me know if there is anything else I can provide.

**Comment by victorolinasc** [comment]
I'll try to take a look later on today. Can you share:

- System OS and version
- Erlang version
- Elixir version
- Joken version

My first guess is that something on your hot path is using `:crypto.strong_rand_bytes` and that locks a scheduler (a discussion about it can be seen [here](https://github.com/elixir-plug/plug/issues/629) on the Plug issue about request id using strong_rand_bytes).

**Comment by Shayon** [comment]
Of course I forgot all that important information :smile: 
Our elixir application is running in a docker container FYI
* Base System OS and version: `Ubuntu 16.04.6 LTS`
* Docker container OS and version: `Alpine 3.9.4`
* Erlang version: `Erlang/OTP 22.0.7`
* Elixir version: `1.8.2`
* Joken version: `2.1.0`
* Jose version: `1.9.0`

**Comment by victorolinasc** [comment]
Thanks for the info! I can't look at it more closely right now but I'll ask just one more information: can you say the result of running `:crypto.info_lib()`? One thing to try on this scenario is to run ES512 entirely through the openssl version Erlang has available to in the container.

Also, can you verify that `JOSE.crypto_fallback/0` is `false`?

**Comment by Shayon** [comment]
Here's the info real quick:
`:crypto.info_lib()`: `[{"OpenSSL", 269488175, "OpenSSL 1.1.1b  26 Feb 2019"}]`
`JOSE.crypto_fallback()`: `false`


Now I'm going to try and figure out how to "run ES512 entirely through the openssl version Erlang has available to in the container." :crossed_fingers:

**Comment by Shayon** [comment]
I'm having some trouble figuring out how exactly I am supposed to run ES512 entirely through openssl while using Joken... any pointers?

**Comment by Shayon** [comment]
Hey @victorolinasc have you been able to put any time into this? Or is there anything else I can do to help discover what the solution may be?

**Comment by victorolinasc** [comment]
Sorry @Shayon I still haven't found some time to look into this. I'll try to make some room tonight. Hope to reply to you in max 24hs.

Once again, sorry for the long wait. I still believe/guess this is not a Joken issue per se. Could you try using a different algorithm? ES512 is based on `secp521r1` and is specified [here](https://tools.ietf.org/html/rfc7518#page-9).

From my previous experience this is not the most recommended algorithm and is also not the best performing one (we have a bench suite on the project). Most big implementations on the wild that I know of prefere RS*** algorithms. If you could at least attest that this works better than we could narrow it down to the implementation of elliptic curve cryptography. 

My reasoning here will be to see if I can generate that load locally and test it with several implementations (HS, RS, ES, PS mainly).

**Comment by victorolinasc** [comment]
I couldn't reproduce it, but I am trying to come up with something you can test on your server.

The core of ES512 is this:

```erlang
:public_key.verify(message, :sha512, der_signature, ec_public_key)
```

Here we have:
- message is the the first two parts of the token
- der_signature is the third part of the token der encoded
- ec_public_key is an erlang `ECPublicKey` record which contains the point on the curve `:secp521r1`

I truly think that you are reaching a locking in the crypto implementation as the syscall that is most called is futex and we don't lock anything explicitely neither on Joken nor on JOSE.

If you are following the Erlang Ecosystem Foundation newsletters the security team has in one of its goals to re-architect the crypto module to avoid using so many locks. I've read it on the newsletter but that can't be searched online and I've unfortunately deleted the e-mail =/

The whole implementation of the ES512 is [here](https://github.com/potatosalad/erlang-jose/blob/master/src/jose_jwk_kty_ec.erl#L233) on JOSE. There you can check out how to der_encode the signature and try it on your server to see if it is purely the crypto implementation calling `:public_key` directly.

**Comment by victorolinasc** [comment]
Hi @Shayon have you figured it out whether there is something in Joken creating the lock?

**Comment by Shayon** [comment]
So, I don't think it is necessarily Joken that is at fault, I was able to reproduce using `JOSE` only a while back.  I'm not really an expert at this so I'm having trouble debugging it.  Furthermore, since the problem isn't going  away I've had to spend my time on modifying my service so it can run on multiple hosts in order to scale (sooner than I would have liked :disappointed:)

Like I said, I think this is not really a Joken issue so you can close the issue if you like.  It's a pity I couldn't get to the bottom of this though

**Comment by victorolinasc** [comment]
Like I said, I truly think this is a crypto bug that might be addressed on
OTP 23.

One channel you could ask about this is the erlang slack community. Also,
it would be nice to open a bug on the OTP jira. You have a lot of good data
to share and I guess it would be a welcome report.



Em seg, 30 de set de 2019 14:30, Shayon Javadizadeh <
notifications@github.com> escreveu:

**Comment by Shayon** [comment]
Okay, I'll try to do that once I am able to get things stable with my service.  I really appreciate the help, Victor! :1st_place_medal:

**Comment by victorolinasc** [comment]
No worries! Sorry if I can't help you more =/

Hope things get sorted out!
