### ISSUE TITLE
Argument error when generating token

### ISSUE THREAD

**Issue by pedroseabra1091** [joken-elixir/joken#247]
When generating the token while defining the signer explicitly I get: 
```
** (ArgumentError) argument error: [[], {:jose_jws, {:jose_jws_alg_rsa_pkcs1_v1_5, :RS256}, :undefined, %{"typ" => "JWT"}}, %{"aud" => "Joken", "exp" => 1568637168, "iat" => 1568629968, "iss" => "Joken", "jti" => "2n2e9990n2g0g8v1fg0000b3", "nbf" => 1568629968}]
    (jose) src/jose_jwt.erl:184: :jose_jwt.sign/3
    (joken) lib/joken/signer.ex:119: Joken.Signer.sign/2
    (joken) lib/joken.ex:364: Joken.encode_and_sign/3
    (joken) lib/joken.ex:210: Joken.generate_and_sign/4
```

I am currently creating the signer through the config file like stated in (https://hexdocs.pm/joken/assymetric_cryptography_signers.html#content):
```
config :joken,
  rsa_key: [
    signer_alg: "RS256",
    key_pem: "
    -----BEGIN PUBLIC KEY-----
    ....
    -----END PUBLIC KEY-----"
  ]
```

**Comment by victorolinasc** [comment]
Hi @pedroseabra1091 

It seems that your PEM is not properly formatted. You are using single quotes (`"`) for a multi line string. That preserves the spaces in between.

Try setting your PEM like:

```elixir
config :joken,
  rsa_key: [
    signer_alg: "RS256",
    key_pem: """
    -----BEGIN PUBLIC KEY-----
    ....
    -----END PUBLIC KEY-----
    """
  ]
```

It is important that the final triple quotes be aligned with where each starts so that Elixir will trim it automatically.

Please tell me if that works

**Comment by pedroseabra1091** [comment]
Hey @victorolinasc !
Still breaks, however, the problem isn't the same. Now when I try to `generate_and_sign` pops the following error: 
```
14:36:26.873 [error] Process #PID<0.306.0> raised an exception
** (Joken.Error) Can't sign your token because couldn't create a signer.

To create a signer we need a key in config.exs. You can define
a key in your config.exs in several ways: (...)
```

Could it be a badly sanitized private key?

**Comment by victorolinasc** [comment]
That is strange....

Try this please: 

```elixir
%Joken.Signer{} = signer = Joken.Signer.parse_config(:rsa_key)
defmodule MyToken do
    use Joken.Config
    def token_config, do: %{}
end
token = "xxxxx"
MyToken.verify_and_validate(token, signer)
```

**Comment by pedroseabra1091** [comment]
I already figured it out. I was missing the signer argument in the `generate_and_sign`. I was only sending the extra claims and the signer

**Comment by victorolinasc** [comment]
Nice! Can I close this then?

**Comment by pedroseabra1091** [comment]
I was missing the token_config actually!
Yeah! Thanks for the help 🙏

**Comment by victorolinasc** [comment]
It must be a valid PEM string. PEM can be split into multi lines or not.  THe issue you had first was that your multi-line PEM had spaces at the beginning of the lines because of the single quote.

So, if the PEM is on an ENV variable it just needs to be a valid PEM file.

**Comment by victorolinasc** [comment]
@pedroseabra1091 I'll be closing this one. If you need any help feel free to re-open it.

**Comment by felipersi** [comment]
my fault that let this error happen was that I was not breaking the key into lines with \n.

After adjusting the \n at the end of each line, the certificate was understood by reticulum.
