### ISSUE TITLE
Different behavior of %Joken.Claim{} and Joken.Config.add_claim 

### ISSUE THREAD

**Issue by tokachev** [joken-elixir/joken#249]
When I try to run this 
`Map.put(%{}, "iat", %Joken.Claim{generate: nil, validate: nil})`
It's ok, and I receive 
`%{"iat" => %Joken.Claim{generate: nil, options: [], validate: nil}}`

But in case 
`%{}|> Joken.Config.add_claim("iat", nil, nil)`

I get error 

> ** (Joken.Error) Claim configuration is not valid. You must have either a generation function or a
validation function.
> 

Probably it's expected behavior, but at least it's a bit misleading

Elixir version is 1.9.1. Joken version is 2.1.0

**Comment by victorolinasc** [comment]
Yep! That is a bug!

Thanks for letting us know. I'll work through a patch. Though cannot do it now.

Once again, thanks for looking into it!

**Comment by victorolinasc** [comment]
@tokachev upon further looking into this, I think the function call version is better as its meaning is exactly to provide validation. 

Adding a claim with only nil options is a strange thing. The check is if both are nil. 

I'll try to enhance the error message, but I really think one should not add claims without validation and verification.

Thanks for reporting it though. Feel free to re-open if you think more discussion is needed to clarify this.

**Comment by victorolinasc** [comment]
I've been a really bad reader... the message seems clear enough to me in saying that either one is needed. I think it is expected that creating the struct by hand can generate invalid values. 

Or we could add an always passing verification function? What do you think @tokachev ?

**Comment by victorolinasc** [comment]
The message even says currently: 

```
If both are nil you don`t need a Joken.Claim configuration. You can pass any map of values
to `Joken.Config.generate_and_sign/3`. Verify will only use claims that have a validation
function on your configuration. Example:
```

**Comment by tokachev** [comment]
@victorolinasc I don't think that to add an always passing verification function is a good idea. 

Yes, the message is rather clear. Probably it's worth to remove mentioning of usage %Joken.Claim in documentation. Because such approach can lead to generation of invalid values (e.g. `%Joken.Claim{generate: nil, validate: nil}`). As you know if user have ability to do something wrong, he will do it)

What do you think?

**Comment by victorolinasc** [comment]
Sorry for the long delay! I agree with you that we can remove it or rephrase it better. I think that adding that the function is just a helper for building a struct helps people think of how it is implemented and then they might come with different ways of interacting with it.

What do you think is better?

**Comment by victorolinasc** [comment]
@tokachev I'll leave the docs as is for now. If you can think of a better phrasing there, please, send a PR for further discussions!

Thanks once again for your input!
