### ISSUE TITLE
Create Joken.Signer from OpenSSH-style key

### ISSUE THREAD

**Issue by scouten** [joken-elixir/joken#267]
I would like to be able to create a `Joken.Signer` struct from an OpenSSH-style key instead of the PEM format. If this is possible using the existing code, I would welcome a quick code example.

Thanks!

**Comment by victorolinasc** [comment]
Hi @scouten ! 

Unfortunately there is no built-in way to do that. You can transform your openssh-style key into pem with openssl or ssh-keygen which I believe you used one of them to generate the key. 

This is an example of getting a public key from an rsa openssh key file:

`ssh-keygen -f my_openssh_key -e -m rsa`

With that you could create a signer that can verify tokens but not sign it.

OpenSSH private key files are already PEM encoded, but I haven't had any success to read them in erlang/elixir/jose yet.

Hope this helps!

**Comment by victorolinasc** [comment]
Just to let you know I've opened an issue on JOSE about this: https://github.com/potatosalad/erlang-jose/issues/96

**Comment by victorolinasc** [comment]
I'll close this as it is related to JOSE.
