### ISSUE TITLE
Tried switching to 256x256 and I got to ~50 FID at 50k iterations. Also I got a roughly 4x slowdown when pl regularization kicked in and had to disable it.

### ISSUE THREAD

**Issue by crowellcindy** [joken-elixir/joken#299]
Tried switching to 256x256 and I got to ~50 FID at 50k iterations. Also I got a roughly 4x slowdown when pl regularization kicked in and had to disable it.

```
bin/stylegan2_pytorch --data ../imgs/ --image-size 256 --batch_size 8 --gradient_accumulate_every 2 --ttur_mult 1
```

__Originally posted by @GetsEclectic in https://github.com/lucidrains/stylegan2-pytorch/issues/111#issuecomment-674029284__

**Comment by victorolinasc** [comment]
Wrong repo? :)
