### ISSUE TITLE
ES256 does not return

### ISSUE THREAD

**Issue by Kloenk** [joken-elixir/joken#311]
When using a signer with an `ES256` algorithm, generate_and_sign does not return, but hangs forever.

**Comment by victorolinasc** [comment]
Can you paste an example key or source code to investigate? This seems more like a crypto/OpenSSL issue.

I'd be glad to help if there is an example code

**Comment by victorolinasc** [comment]
I'll be closing the issue because can't reproduce. If you can provide a reproducible project I can take a look into it.

**Comment by Kloenk** [comment]
Sorry, completely forgot this. Now I'm not even sure anymore how I produced the error. Sorry for that
