### ISSUE TITLE
Can't override Joken.Config.validate

### ISSUE THREAD

**Issue by blagh** [joken-elixir/joken#324]
Currently, if you attempt to specify two arguments like so:

    @impl true
    def validate(claims, context) do
       ... etc ...
    end

You get a compiler warning that a previous clause always matches.

If you specify with only one argument:

    @impl true
    def validate(claims) do
       ... etc ...
    end

You get a compiler error that `validate/1` conflicts with defaults from `validate/2`.

Here is a PR with a first pass at fixing the issue: https://github.com/joken-elixir/joken/pull/323

**Comment by victorolinasc** [comment]
Merged :) Thanks!
