### ISSUE TITLE
function :crypto.hmac/3 is undefined or private

### ISSUE THREAD

**Issue by metehan** [joken-elixir/joken#348]
My code produces an error `function :crypto.hmac/3 is undefined or private` on docker container. Same code works well on localhost and other docker containers. 

```elixir
lib/spill_web/plugs/jwt_token.ex
  def create(claims \\ %{}) do
    generate_and_sign(claims, @signer)
  end
  def create_and_take(claims \\ %{}) do
    case create(claims) do
      {:ok, token, _} -> token
      _               -> "token-creation-failed"
    end
  end
```
Stack trace:
```
 crypto nofile:crypto.hmac/3
 jose src/jws/jose_jws.erl:311:jose_jws.sign/4
 jose src/jwt/jose_jwt.erl:173:jose_jwt.sign/3
 joken lib/joken/signer.ex:119Joken.Signer.sign/2
 joken lib/joken.ex:365Joken.encode_and_sign/3
```
Versions:
```
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:3:3] [ds:3:3:10] [async-threads:1] [jit]
Elixir 1.12.3 (compiled with Erlang/OTP 24)
{:joken, "~> 2.4"},

Linux b4756b1a72ab 5.4.0-1050-kvm #52-Ubuntu SMP Fri Nov 12 11:00:20 UTC 2021 x86_64 GNU/Linux
(Official elixir docker container)
```

What may cause the problem?

**Comment by victorolinasc** [comment]
Sorry for the long delay here =/

You probably switched OTP versions without re-compiling JOSE. Can you please paste here what is the version of:

- joke
- jose
- OTP
- elixir
- openssl library

You should probably force the jose version with:

```elixir
{:jose, "~> 1.11.2", override: true}
```

Then recompile on OTP 24+ with `mix deps.compile --force` (don't forget to add `MIX_ENV=test` when compiling do test).

**Comment by victorolinasc** [comment]
@metehan did it work?

**Comment by metehan** [comment]
Yes it did problem was opt version on the server.

**Comment by victorolinasc** [comment]
Thanks!
