### ISSUE TITLE
Disabled linting tasks in GitHub Actions

### ISSUE THREAD

**Issue by kianmeng** [joken-elixir/joken#364]
Based on https://github.com/joken-elixir/joken/runs/6446435740?check_suite_focus=true

There is not specify Elixir/Erlang combination version set for linting related tasks. Is this intentional? Should we enable this back?

```
89     - name: Check source code format
90       run: mix format --check-formatted
91       if: ${{ matrix.lint }}
```

**Comment by victorolinasc** [comment]
I will reconfigure the CI :) Thanks for catching this!
