### ISSUE TITLE
Help with signing token with 2048-bit RSA private-key

### ISSUE THREAD

**Issue by v0i4** [joken-elixir/joken#376]
Hi guys, i'm trying to integrate our app with MuxAPI.

Mux generates for me: "2048-bit RSA key-pair and returns the private key and the public key. "

Then I need to sign my token with this private-key.

I've tried to put this key into a file and read it using the PEM example available in signers docs, but no success..
 signer = Joken.Signer.create("RS256", %{"pem" => rsa_pem})

** (ArgumentError) argument error: [[], {:jose_jws, {:jose_jws_alg_rsa_pkcs1_v1_5, :RS256}, :undefined, %{"typ" => "JWT"}}, %{"aud" => "rt"}]
    (jose 1.11.2) src/jwt/jose_jwt.erl:184: :jose_jwt.sign/3
    (joken 2.5.0) lib/joken/signer.ex:128: Joken.Signer.sign/2
    (joken 2.5.0) lib/joken.ex:361: Joken.encode_and_sign/3
    (live_admin 0.1.0) lib/live_admin/stream/stream_live.ex:75: LiveAdmin.StreamLive.sign_jwt/3
    (live_admin 0.1.0) lib/live_admin/stream/stream_live.ex:88: LiveAdmin.StreamLive.fetch_token/0

also tried:
  signer = Joken.Signer.create("RS256", private_key)
but when i run validation:
{:error, :signature_error}

Any ideas about how to proceed?
Thanks

**Comment by victorolinasc** [comment]
Very strange...

This is our example RSA key in PEM format https://github.com/joken-elixir/joken/blob/main/config/test.exs#L41-L93

Is the value of your variable in the same format as these lines?

**Comment by v0i4** [comment]
** (MatchError) no match of right hand side value: {:error, {:asn1, {{:invalid_value, 3}, [{:asn1rt_nif, :decode_ber_tlv, 1, [file: 'asn1rt_nif.erl', line: 89]}, {:"OTP-PUB-KEY", :decode, 2, [file: '../src/OTP-PUB-KEY.erl', line: 1233]}, {:public_key, :der_decode, 2, [file: 'public_key.erl', line: 345]}, {:jose_public_key, :pem_entry_decode, 1, [file: 'src/jose_public_key.erl', line: 192]}, {:jose_jwk_pem, :from_binary, 1, [file: 'src/jwk/jose_jwk_pem.erl', line: 31]}, {:jose_jwk, :from_pem, 1, [file: 'src/jwk/jose_jwk.erl', line: 449]}, {JOSE.JWK, :from_pem, 1, [file: 'lib/jose/jwk.ex', line: 186]}, {Joken.Signer, :create, 3, [file: 'lib/joken/signer.ex', line: 87]}, {:elixir, :"-eval_external_handler/1-fun-2-", 4, [file: 'src/elixir.erl', line: 298]}, {:erl_eval, :do_apply, 7, [file: 'erl_eval.erl', line: 748]}, {:erl_eval, :expr, 6, [file: 'erl_eval.erl', line: 492]}, {:elixir, :eval_forms, 3, [file: 'src/elixir.erl', line: 288]}, {Module.ParallelChecker, :verify, 1, [file: 'lib/module/parallel_checker.ex', line: 100]}, {IEx.Evaluator, :eval_and_inspect, 3, [file: 'lib/iex/evaluator.ex', line: 329]}, {IEx.Evaluator, :eval_and_inspect_parsed, 3, [file: 'lib/iex/evaluator.ex', line: 303]}, {IEx.Evaluator, :parse_eval_inspect, 3, [file: 'lib/iex/evaluator.ex', line: 292]}, {IEx.Evaluator, :loop, 1, [file: 'lib/iex/evaluator.ex', line: 187]}, {IEx.Evaluator, :init, 4, [file: 'lib/iex/evaluator.ex', line: 32]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}}
    (public_key 1.13) public_key.erl:349: :public_key.der_decode/2
    (jose 1.11.2) src/jose_public_key.erl:192: :jose_public_key.pem_entry_decode/1
    (jose 1.11.2) src/jwk/jose_jwk_pem.erl:31: :jose_jwk_pem.from_binary/1
    (jose 1.11.2) src/jwk/jose_jwk.erl:449: :jose_jwk.from_pem/1
    (jose 1.11.2) lib/jose/jwk.ex:186: JOSE.JWK.from_pem/1
    (joken 2.5.0) lib/joken/signer.ex:87: Joken.Signer.create/3
    iex:157: (file)


with the example key it worked.. there is something wrong with the format of my key..
it should work with 2048 bit RSA key, right?

**Comment by v0i4** [comment]
it worked! 

{:ok, rsa_pem} = signing_key |> Base.decode64()
signer = Joken.Signer.create("RS256", %{"pem" => rsa_pem})

thanks!
