### ISSUE TITLE
Unable to set the type in the JWT header

### ISSUE THREAD

**Issue by jkbbwr** [joken-elixir/joken#379]
Any attempt to set the type is always overwritten. 
My API requires that the type in the header is set to `JWS`

Currently working around it by hacking the struct cirectly but this is obviously not portable.

Please advise.

**Comment by victorolinasc** [comment]
Can you provide a simple example here that reproduces the problem.

**Comment by victorolinasc** [comment]
If I understand the issue correctly, custom header parameters (as is the `typ` claim on a JWS token) can be set. THere is a dedicated guide on docs here https://hexdocs.pm/joken/custom_header_arguments.html

**Comment by victorolinasc** [comment]
Sorry. Replied too fast without looking more deeply into it. We are setting it on a nasty Map.merge call.

I'll fix this and release a new version.

**Comment by victorolinasc** [comment]
This is fixed on master and will be released soon :)

Nice catch! 

Either way it is on the specification that if the `typ` header claim is present it is RECOMMENDED that its value is `JWT`. Nonetheless we shouldn't enforce it if it is just a recommendation.

**Comment by chanphiromsok** [comment]
how can I remove type : "JWT" from decode header Joken.encode_and_sign ? after called it I check the source code see it use by default
