### ISSUE TITLE
[DISCUSSION] Hiding sensitive data

### ISSUE THREAD

**Issue by spencerdcarlson** [joken-elixir/joken#383]
What are your thoughts about [deriving Inspect](https://hexdocs.pm/elixir/Inspect.html) for the `Joken.Signer` struct so that the `jwk` attribute is excluded?

**Reference** 
* [erlef sensitive data - elixir](https://erlef.github.io/security-wg/secure_coding_and_deployment_hardening/sensitive_data.html#elixir)

**Comment by victorolinasc** [comment]
I think this is a very nice addition :) Though I don't think the way it is here is proper. We should hide private keys and not ALL jwks IMHO.

This maybe is better suited to be implemented in JOSE as it stands currently. I have a WIP about doing a crypto layer that we can exchange between JOSE and Joken but haven't had the time to finish it yet...

**Comment by spencerdcarlson** [comment]
That makes sense. I took a quick stab at it in [PR 139](https://github.com/potatosalad/erlang-jose/pull/139)

**Comment by victorolinasc** [comment]
I've updated JOSE dependency and so this is currently on master now. 

THanks a lot @spencerdcarlson for the nice discussion!
