### ISSUE TITLE
Runtime error for invalid token

### ISSUE THREAD

**Issue by leggebroten** [joken-elixir/joken#387]
Running `verify_and_validate` for bad token will crash the process

```elixir
    token = "155345097360937867.108540985.1090485"
    Token.verify_and_validate(token)
```
Yields:

```
     ** (Jason.DecodeError) unexpected byte at position 0: 0xD7
     code: Token.verify_and_validate(token)
     stacktrace:
       (jason 1.4.0) lib/jason.ex:92: Jason.decode!/2
       (joken 2.5.0) lib/joken.ex:135: Joken.peek_header/1
       (joken_jwks 1.6.0) lib/joken_jwks.ex:62: JokenJwks.get_token_kid/1
       (joken_jwks 1.6.0) lib/joken_jwks.ex:53: JokenJwks.before_verify/2
       (joken 2.5.0) lib/joken/hooks.ex:199: anonymous fn/3 in Joken.Hooks.run_before_hook/3
       (elixir 1.14.1) lib/enum.ex:4751: Enumerable.List.reduce/3
       (elixir 1.14.1) lib/enum.ex:2514: Enum.reduce_while/3
       (joken 2.5.0) lib/joken/hooks.ex:196: Joken.Hooks.run_before_hook/3
       (joken 2.5.0) lib/joken.ex:255: Joken.verify/3
       (joken 2.5.0) lib/joken.ex:299: Joken.verify_and_validate/5
       test/joken_bug_test.exs:24: (test)
```

A test
[joken_bug_test.exs.zip](https://github.com/joken-elixir/joken/files/10356643/joken_bug_test.exs.zip)

**Comment by victorolinasc** [comment]
I think you are using old versions of the dependencies here. I see you are using `joken_jwks` (which is nice :)) and I think the version of joken currently is a bit old there. I might update it soon...

Either way, I can't reproduce this with current master:

![image](https://user-images.githubusercontent.com/376386/215358099-d3725ea8-26e9-4352-a169-8b6b7cb501cc.png)

If you can show a reproduction scenario with current master, please feel free to reopen the issue!
