### ISSUE TITLE
Missing v2.6.0 tag on GitHub

### ISSUE THREAD

**Issue by alco** [joken-elixir/joken#397]
When viewing online docs for the latest version which at this time is v2.6.0, clicking on any links to the source code takes the user to a 404 page. For instance, navigating to https://github.com/joken-elixir/joken/blob/v2.6.0/lib/joken.ex#L1 shows this:
![image](https://github.com/joken-elixir/joken/assets/207748/bc795759-432a-4347-acbf-5bf6ff0cf67d)

This can be fixed by pushing the v2.6.0 tag to GitHub.

**Comment by Xunjin** [comment]
Great find @alco.

Pinging @victorolinasc just for the fun :yum:

**Comment by victorolinasc** [comment]
Sorry! My bad! Just pushed it...

I'll update the release actions here (that I am not using unfortunately...).
