### ISSUE TITLE
Benchmark files reference :default_key instead of :default_signer

### ISSUE THREAD

**Issue by ktekinay** [joken-elixir/joken#398]
The benchmark files that use `Joken.Config` reference `:default_key`, but this will not change the algorithm. Instead it should use `:default_signer`.

Example:

```
# bad
defmodule HS256Auth do
  use Joken.Config, default_key: :hs256
end

# GOOD!
defmodule HS256Auth do
  use Joken.Config, default_signer: :hs256
end
```

Without the change, the benchmarks appear to work but are not actually testing anything as the tokens are always generated and validated with the default_signer, and validation fails silently.

**Comment by victorolinasc** [comment]
My bad! Will fix it soon!

Thanks for raising the issue!

**Comment by victorolinasc** [comment]
Fixed now on main :) Thanks once again!
