### ISSUE TITLE
EdDSA support

### ISSUE THREAD

**Issue by patatoid** [joken-elixir/joken#439]
I can see arising more and more JWTs signed with EdDSA keys.

Does Joken support signing and/or verifying with such keys?

Thank you for your work!

**Comment by victorolinasc** [comment]
We do support all algorithms as JOSE supports. 

A list of them can be seen here: https://github.com/potatosalad/erlang-jose#json-web-signature-jws-rfc-7515

If you want to generate a test signer for this, you can do:

```elixir
jwk = JOSE.JWK.generate_key({:okp, :Ed25519})
jws = JOSE.JWS.from(%{"alg" => "EdDSA"})
signer = %Joken.Signer{alg: "EdDSA", jwk: jwk, jws: jws}

# Generate example token
token = Joken.generate_and_sign! %{}, %{hello: :world}, signer
# => "eyJhbGciOiJFZERTQSJ9.eyJoZWxsbyI6IndvcmxkIn0.omIviQzI4r0wgOaUHI3QLKbv9gjaBAEby25WV0lpAZuUN--LmGYY2YxEPjLITU1H4GfVK5uKxyx2hMN7BiBxAA"

# Now verify it is correct
Joken.verify_and_validate %{}, token, signer
# => {:ok, %{"hello" => "world"}}
```

Does this help?

**Comment by patatoid** [comment]
yes definitely, thank you!
